baseURL: "https://nortrom1213.github.io/"
title: Kaijie Xu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

buildfuture: true

taxonomies:
    tag: tags

menu:
    main:
    - name: News
      url: news/
      weight: 1
    - name: Publications
      url: publications/
      weight: 2
    - name: Notebook
      url: notebook/
      weight: 3

params:
    description: "Kaijie (Jay) Xu, PhD Student at McGill University — Publications & News"
    author: Kaijie Xu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["news","publications","notebook"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true

    profileMode:
          enabled: true
          title: Kaijie (Jay) Xu
          subtitle: >
            I’m a second-year PhD candidate in Computer Science at McGill University, supervised by <a href="https://www.sable.mcgill.ca/~clump/" style="color:#0066cc;">Dr Clark Verbrugge</a>; previously, I completed a B.A. in Computer Science & Applied Mathematics at UC Berkeley and an M.Sc. at Imperial College London under <a href="https://cq615.github.io/" style="color:#0066cc;">Dr Chen Qin</a> (primary) and <a href="https://cheng-01037.github.io/" style="color:#0066cc;">Dr Cheng Ouyang</a> (co-supervisor).<br>
            I'm interested in procedural content generation, game AI, computer vision in games, large language models, and optimization & evolutionary computation.

          imageUrl: "me.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
          - name: News
            url: news/
          - name: Publications
            url: publications/
          - name: Notebook
            url: notebook/


    socialIcons:
        #- name: CV
        #  url: cv.pdf
        - name: Email
          url: mailto:kaijie.xu2@mail.mcgill.ca
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=zh-CN&user=Ks6qgVQAAAAJ
        - name: LinkedIn
          url: https://www.linkedin.com/in/kaijie-xu-051705263/
        - name: GitHub
          url: https://github.com/Nortrom1213

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Kaijie Xu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2